### ISSUE TITLE
12/6/2020: ανακολουθία

### ISSUE THREAD

**Issue by Hector-Xavier** [iMEdD-Lab/open-data#3]
Στο regions_greece_cases.csv, στις 12/6/2020 εμφανίζεται ανακολουθία σε σχέση με τις προηγούμενες ημέρες. Αλλαξε μήπως η σειρά με την οποία αναγράφονται οι περιοχές στη βάση του ΕΟΔΥ;

**Comment by capitaine** [comment]
Please can you keep files structure stable ? Otherwise it is impossible to automate their processing. It is the second time greece.csv changes (at least of what we observed). On 12/6 it contains a lot of garbage rows like "<<<<<<< HEAD", "=======", and also duplicate rows. Last time we had a problem it was just on first and last rows, so it was easy to remove, but now there is no apparent rule. It is unusable like that. Also there is no definition for "Απροσδιόριστος,Unknown". What does it cover ? Is it the sum of refugees + crouazeroploio + ? or something else ? Thank you for your efforts.

**Comment by troboukis** [comment]
There was a mixup with the merge at the server for a few hours. Sorry about that. We do our best to keep this dataset updated and in good shape. But staff like that do happen. 
We'll add a readme file on Monday or Tuesday at the latest about each CSV file.

**Comment by kellykiki** [comment]
> Στο regions_greece_cases.csv, στις 12/6/2020 εμφανίζεται ανακολουθία σε σχέση με τις προηγούμενες ημέρες. Αλλαξε μήπως η σειρά με την οποία αναγράφονται οι περιοχές στη βάση του ΕΟΔΥ;

Διορθώθηκε σε επόμενο commit. Έχει αποκατασταθεί. Ευχαριστούμε για την επικοινωνία!

**Comment by capitaine** [comment]
Fine! it works. Thank you
