### ISSUE TITLE
Mismatch in "alert" and "chart" numbers of cases

### ISSUE THREAD

**Issue by sebkkom** [iMEdD-Lab/open-data#4]
Hello @iMEdD-Lab,

I've noticed a continuous mismatch in the number of cases that appears in the "alert" text (on the top of the page) and the "chart" section on the left sidebar - I'm attaching a couple of screenshots that demonstrate this.

![12th of August](http://www.sebkkom.info/images/1208.png)

![13th of August](http://www.sebkkom.info/images/1208.png)

![14th of August](http://www.sebkkom.info/images/1408.png)

I only had a very quick look at your code so I couldn't find how the alerts text and the charts numbers are generated but I'd be happy to get some guidance and contribute to fix this in the case that it's a coding issue.

**Comment by troboukis** [comment]
Hey, thanks for contacting us.
This happens because EODY corrects duplicate positive results of previous days, but fails to disclose which days those duplicates refer to. For instance, let’s say that on Day 1 we have 10 total cases. On Day 2, we have 5 new cases, which means that EODY should announce 15 total cases. However, the total number of cases announced on Day 2 is 13. This means that there were 2 duplicate cases on Day 1, which are corrected on Day 2. 3 cases and 15 total cases will be recorded in our dataset on Day 2. Indicatively, corrected numbers of cases are presented in greeceTimeline.csv on May 22, May 27, May 29, May 30, June 1, June 2, June 10, June 11, June 16, June 23, June 25, June 29, June 30, July 2, July 5.
If you wish to use the exact number of new cases officially announced each day, run through the pdfsDataFrame.csv for information extracted from the official reports published in PDF files by EODY.

We have a readme file where we explain everything in detail. https://github.com/iMEdD-Lab/open-data/blob/master/COVID-19/README.md

**Comment by sebkkom** [comment]
Thanks a lot for taking time to clarify this!
